"""Add product_workflows table

Revision ID: 90da12bca124
Revises: b7b0195159c8
Create Date: 2026-01-26 23:18:44.566215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90da12bca124'
down_revision: Union[str, None] = 'b7b0195159c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('workflow_definition', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_workflows_endpoint'), 'product_workflows', ['endpoint'], unique=False)
    op.create_index(op.f('ix_product_workflows_id'), 'product_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_product_workflows_product_id'), 'product_workflows', ['product_id'], unique=False)
    op.drop_index(op.f('ix_mqtt_subscriptions_id'), table_name='mqtt_subscriptions')
    op.drop_table('mqtt_subscriptions')
    op.drop_index(op.f('ix_mqtt_connection_status_id'), table_name='mqtt_connection_status')
    op.drop_table('mqtt_connection_status')
    op.drop_index(op.f('ix_mqtt_configs_id'), table_name='mqtt_configs')
    op.drop_table('mqtt_configs')
    op.drop_index(op.f('idx_docker_images_name'), table_name='docker_images')
    op.drop_index(op.f('idx_docker_images_name_tag'), table_name='docker_images')
    op.drop_index(op.f('idx_docker_images_tag'), table_name='docker_images')
    op.create_index(op.f('ix_docker_images_id'), 'docker_images', ['id'], unique=False)
    op.create_index(op.f('ix_docker_images_name'), 'docker_images', ['name'], unique=False)
    op.create_index(op.f('ix_docker_images_tag'), 'docker_images', ['tag'], unique=False)
    op.alter_column('email_templates', 'data_requirements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('email_templates', 'attachments_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(op.f('email_templates_product_id_fkey'), 'email_templates', type_='foreignkey')
    op.create_foreign_key(None, 'email_templates', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('idx_event_subscriptions_product_event'), table_name='event_subscriptions')
    op.drop_index(op.f('idx_event_subscriptions_product_id'), table_name='event_subscriptions')
    op.alter_column('orchestrator_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'env_vars',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'env_vars',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('orchestrator_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_event_subscriptions_product_id'), 'event_subscriptions', ['product_id'], unique=False)
    op.create_index(op.f('idx_event_subscriptions_product_event'), 'event_subscriptions', ['product_id', 'event_type'], unique=True)
    op.drop_constraint(None, 'email_templates', type_='foreignkey')
    op.create_foreign_key(op.f('email_templates_product_id_fkey'), 'email_templates', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('email_templates', 'attachments_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('email_templates', 'data_requirements',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_docker_images_tag'), table_name='docker_images')
    op.drop_index(op.f('ix_docker_images_name'), table_name='docker_images')
    op.drop_index(op.f('ix_docker_images_id'), table_name='docker_images')
    op.create_index(op.f('idx_docker_images_tag'), 'docker_images', ['tag'], unique=False)
    op.create_index(op.f('idx_docker_images_name_tag'), 'docker_images', ['name', 'tag'], unique=True)
    op.create_index(op.f('idx_docker_images_name'), 'docker_images', ['name'], unique=False)
    op.create_table('mqtt_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('broker_host', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('broker_port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('use_tls', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verify_cert', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('keep_alive', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clean_session', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('topic_prefix', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topic_pattern', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('use_shared_subscriptions', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('shared_group', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('qos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('mqtt_configs_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mqtt_configs_pkey')),
    sa.UniqueConstraint('product_id', name=op.f('mqtt_configs_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mqtt_configs_id'), 'mqtt_configs', ['id'], unique=False)
    op.create_table('mqtt_connection_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_connected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_disconnected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('connection_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('messages_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subscribed_topics_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('broker_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('mqtt_connection_status_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mqtt_connection_status_pkey')),
    sa.UniqueConstraint('product_id', name=op.f('mqtt_connection_status_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mqtt_connection_status_id'), 'mqtt_connection_status', ['id'], unique=False)
    op.create_table('mqtt_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mqtt_config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('messages_received', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actions_executed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actions_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mqtt_config_id'], ['mqtt_configs.id'], name=op.f('mqtt_subscriptions_mqtt_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mqtt_subscriptions_pkey'))
    )
    op.create_index(op.f('ix_mqtt_subscriptions_id'), 'mqtt_subscriptions', ['id'], unique=False)
    op.drop_index(op.f('ix_product_workflows_product_id'), table_name='product_workflows')
    op.drop_index(op.f('ix_product_workflows_id'), table_name='product_workflows')
    op.drop_index(op.f('ix_product_workflows_endpoint'), table_name='product_workflows')
    op.drop_table('product_workflows')
    # ### end Alembic commands ###
